exclude: [ "README.md", "package.json", "gulp", "CNAME", "Gemfile", "Gemfile.lock", ".idea", "node_modules", "jspm_packages" ]

name: "Nace Logar CV & Portfolio"
description: "As stated above my name is <strong>Nace</strong>, pronounced 'Natse' I started as a windows desktop developer.
              Later on I became web developer working primarily on web pages and business web applications where I actually fell in love with
              CSS, HTML and JS."
url: "http://thecodedestroyer.com"




