import type { Work } from '@shared/types/work.types';

export const previousWork: Work[] = [
  {
    company: 'Spartan Development d.o.o.',
    position: 'Full Stack Developer',
    from: 'Sep 2026',
    to: 'Present',
    tasks: [
      'Shape the technical direction of the studio, from architecture and stack choices to engineering standards and delivery workflows.',
      'Build product and client work end to end across the front-end and back-end.',
      'Lead the adoption of AI engineering workflows, from agentic coding tools to reviewable, repeatable automation.',
      'Educate the team on a modern web stack and modern development practices.',
      'Mentor developers through code review and pair programming.',
    ],
  },
  {
    company: 'Optiweb d.o.o.',
    position: 'Senior Software Developer',
    from: 'Mar 2025',
    to: 'Aug 2026',
    tasks: [
      'Introduced monorepo structure for agency projects, enabling code reuse and accelerating development.',
      'Implemented Vercel for front-end deployments, streamlining development workflows.',
      'Redesigned Optiweb.com using headless CMS with Payload and Next.js, leveraging static generation for enhanced performance.',
      'Contributed to CPQ-based projects, developing sales configuration and pricing tools.',
      'Educated team on AI tools and best practices, improving productivity and fostering innovative AI adoption.',
    ],
  },
  {
    company: 'Bird Buddy d.o.o.',
    position: 'Senior Software Developer',
    from: 'Feb 2023',
    to: 'Feb 2024',
    tasks: [
      'Migrated CMS to Turborepo & Next.js, enhancing scalability.',
      "Introduced 'Editor's Choice' in CMS, boosting content engagement.",
      'Developed ad-centric landing page to optimize marketing.',
      'Launched guest invite management in feeder, enhancing user experience.',
      'Managed CMS backend with NestJS and Prisma for robust operations.',
      'Collaborated on new CMS features, focusing on stability and team synergy.',
    ],
  },
  {
    company: 'Iryo d.o.o.',
    position: 'Senior Frontend Developer',
    from: 'Jan 2019',
    to: 'Feb 2023',
    tasks: [
      'Led an FE team to develop Moshi, a cloud-based app enhancing healthcare management.',
      'Implemented e-signatures and dynamic questionnaires to increase data efficiency.',
      'Used React, Redux, and TailwindCSS for responsive UI design.',
      'Established customer support via Intercom, enhancing user satisfaction.',
      'Ensured app reliability through automated testing with Cypress and Jest.',
    ],
  },
  {
    company: '3fs d.o.o.',
    position: 'Senior Frontend Developer',
    from: 'May 2017',
    to: 'Feb 2023',
    tasks: [
      'Developed major web apps in IoT marketplace and healthcare.',
      'Launched a remote monitoring app for patient ventilators, improving critical care.',
      'Engaged in Agile methodologies for continuous team improvement.',
      'Standardized coding practices across projects using ESLint.',
      'Delivered talks on JavaScript and React, enhancing team skills.',
      'Mentored developers and engaged in pair programming for team growth.',
    ],
  },
  {
    company: 'Infonet d.o.o.',
    position: 'Senior Developer',
    from: 'Aug 2016',
    to: 'May 2017',
    tasks: [
      'Enhanced Java deployment process by introducing Docker to the development team.',
      'Streamlined Java operations with Docker.',
      'Optimized CI/CD with GitLab, enhancing team efficiency.',
      'Built dozdravnika.si for seamless doctor appointments using Angular.js, enhancing user login via Keycloak.',
      'Expanded technical skills by learning Pascal, resolving healthcare bugs.',
    ],
  },
  {
    company: 'Četrta pot d.o.o.',
    position: 'Senior Developer',
    from: 'Dec 2014',
    to: 'Jul 2016',
    tasks: [
      'Developed a web app with Angular.js for real-time bus tracking and arrival times using a Leaflet map.',
      'Migrated Kadris to a modern, single-page app with Angular.js, enhancing efficiency and streamlining processes.',
      'Implemented Jenkins for CI/CD, improving web application deployment workflows.',
      'Created an Angular.js site displaying live runner data via WebSockets and NFC technology.',
    ],
  },
  {
    company: 'pixi labs d.o.o.',
    position: 'Senior Developer',
    from: 'Apr 2012',
    to: 'Apr 2014',
    tasks: [
      'Led a team of 10 in a transition to a scrum-based approach, later focusing on a streamlined team of 5.',
      'Overhauled a desktop application for inventory management tailored to web store sellers.',
      "Developed the application's full stack using ASP.NET MVC for a responsive design.",
      'Contributed to a hackathon to reimagine the application’s frontend using Angular.js.',
    ],
  },
  {
    company: 'E-soft d.o.o.',
    position: 'Developer',
    from: 'Nov 2010',
    to: 'Apr 2012',
    tasks: [
      'Acquired comprehensive knowledge in web page construction, focusing on creating CMS webpages using an internally developed ASP.NET MVC platform.',
      'Enhanced my skills in CSS and JavaScript, with a strong emphasis on collaborative learning alongside experienced team members.',
      'Gained practical experience in DevOps practices, including the maintenance and management of hosted domains and websites on premises servers using Active Directory and Microsoft IIS.',
    ],
  },
  {
    company: 'Infotrans d.o.o.',
    position: 'Developer',
    from: 'Sep 2008',
    to: 'Aug 2010',
    tasks: [
      'Acquired deep knowledge in software development for desktop logistics applications.',
      'Key contributor to a logistics management project enhancing operational efficiency.',
      'Advanced to mentorship, guiding new employees technically and operationally.',
      'Provided customer support through direct communication and Remote Desktop.',
      'Continuously improved software modules, maintaining high operational standards.',
    ],
  },
];
